name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version Number (0.0.1 Format)'
        required: true
        default: '0.0.1'

jobs:
  build:
    name: Build Templates
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    
    - name: Create Release
      run: |
        set -x
        
        dotnet pack Templates/Templates.csproj -p:PackageVersion=${{ github.event.inputs.version }} -o nuget --configuration Release

        assets=()
        for asset in ./nuget/*.nupkg; do
          assets+=("-a" "$asset")
        done
        hub release create "${assets[@]}" -m "v${{ github.event.inputs.version }}" "v${{ github.event.inputs.version }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
