name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version Number (0.0.1 Format)'
        required: true
        default: '0.0.1'

jobs:
  build:
    name: Build Templates
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
          
    - name: Package
      run: dotnet pack Templates/Templates.csproj -p:PackageVersion=${{ github.event.inputs.version }} -o nuget --configuration Release

    - name: Create release
      run: |
        set -x

        assets=()
        for asset in ./nuget/*.nupkg; do
          assets+=("$asset")
        done
        gh release create "v${{ github.event.inputs.version }}" "${assets[@]}" --generate-notes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
